version: "3.9"
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8082"
    volumes:
      - .:/app
    environment:
      NODE_ENV: dev

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - .:/test
    environment:
      NODE_ENV: test

  frontend:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      NODE_ENV: prod
